name = "bolt"
main = "_worker.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "vless-worker-prod"

# Worker configuration
[build]
command = "npm run build"  # or the command you need to build your worker

# Add any environment variables here if needed
[vars]
PROXY_IP = "172.232.238.56"
DEBUG = "true"

# Durable Objects (if needed in future)
#[[durable_objects.bindings]]
#name = "VLESS_STATE"
#class_name = "VlessState"

# KV namespaces (if needed for configuration storage)
[[kv_namespaces]]
binding = "VLESS_CONFIG"
id = "243d995a3bba45e5bad6f08a5484c2d8"
preview_id = "vless-preview-config-id"
